### ISSUE TITLE
Nightly tests failing

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-vscode#855]
It looks like the nightly CI tests have been failing for months:

https://github.com/apache/daffodil-vscode/actions/workflows/nightly.yml

I'm not sure what value the provide over PR and merge actions, but we should either get them working or remove if they don't provide value.

**Comment by scholarsmate** [comment]
Thanks @stevedlawrence.  The current CI tests against VS Code 1.67.2, the earliest version of VS Code supported for v1.4.0 of the extension.  The nightly tests are designed to run against the latest stable and insider's builds of VS Code.  We're going to want these to pass in general, especially for the latest stable release.  VS Code 1.67.2 uses node 16 internally and the latest stable uses node 18 internally.  I opened a PR to shift from testing under node 14 and 16, to 16 and 18.  That may help fix some of the tests.

**Comment by arosien** [comment]
For the Windows failures, the message is
> Error: EBUSY: resource busy or locked, rmdir

A likely cause (from [SO](https://stackoverflow.com/questions/55212864/error-ebusy-resource-busy-or-locked-rmdir)) is
> Another way you can trigger this error is if you are running an npm run [command] while cd'd into the directory that its altering. This happened to me where I closed every program and it didn't work, but realized I was inside the dist folder which needed to be removed and rebuilt. This triggered the Error: EBUSY: resource busy or locked, rmdir error in PowerShell and can be reproduced every time.

We are likely cleaning up some directory during the tests while that directory is "being used".

**Comment by arosien** [comment]
#856 [didn't fix the nightly builds completely](https://github.com/apache/daffodil-vscode/actions/runs/6332881859/job/17200120909), the Windows builds are still failing due to the above. Should this issue be reopened, or a new one filed? @scholarsmate @stevedlawrence

**Comment by stevedlawrence** [comment]
I'd vote for reopening this one if #856 didn't completely fix it. Then we have a full record of what PRs were needed to fix the issue.

**Comment by shanedell** [comment]
Between https://github.com/apache/daffodil-vscode/pull/901 and https://github.com/apache/daffodil-vscode/pull/894 these nightly tests might have been fixed. Going to wait till tomorrow to see if it runs any better, if it works I will close this issue.

**Comment by arosien** [comment]
No change, [nightly tests](https://github.com/apache/daffodil-vscode/actions/workflows/nightly.yml) still failing. Seems to be only failing windows and mac when downloading VS Code for the integration tests.

**Comment by arosien** [comment]
looks like the path inside the VSCode artifact changed to something the test code doesn't expect:
```
Downloaded VS Code into /Users/arosien/nteligen/daffodil-vscode/.vscode-test/vscode-darwin-1.67.2
Test error: Error: spawn /Users/arosien/nteligen/daffodil-vscode/.vscode-test/vscode-darwin-1.67.2/Visual Studio Code.app/Contents/MacOS/Electron ENOENT
Exit code:   -2
Failed to run tests: Failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  daffodil-vscode git:(Shanedell/add-root-element-settings) ls /Users/arosien/nteligen/daffodil-vscode/.vscode-test/vscode-darwin-1.67.2
Contents
➜  daffodil-vscode git:(Shanedell/add-root-element-settings) ls /Users/arosien/nteligen/daffodil-vscode/.vscode-test/vscode-darwin-1.67.2/Contents/
CodeResources    Frameworks/      Info.plist       MacOS/           PkgInfo          Resources/       _CodeSignature/
```
